import LpAuditForm from "@/components/forms/LpAuditForm";
import FadeUp from "@/components/ui/FadeUp";
import { siteConfig } from "@/lib/metadata";
import { LP_FORM_ANCHOR, LP_TURNAROUND, type LpVariant } from "@/lib/lp";

/**
 * The conversion section.
 *
 * The left column now says what the audit contains rather than describing it in
 * a paragraph — a visitor who has scrolled this far is deciding whether four
 * questions buys something worth having, and a list answers that faster.
 *
 * Email is the only alternative offered. Click-to-call used to sit here for
 * someone who reached the bottom and still had not filled in the form; it was
 * removed with the rest of the phone CTAs — see LP_PHONE.
 */
/*
 * THE FIVE-BULLET LIST THAT WAS HERE IS GONE, cut 9 Sep 2026.
 *
 * LandingAuditPitch, five sections up, already lists seven things the audit
 * looks at. This listed five more about what comes back, so one free offer was
 * explained in fifteen bullets across two sections. That was a third of the
 * reason the page ran to 22 phone screens.
 *
 * What is left below is the part this section owns and the pitch does not: the
 * turnaround, what it costs the reader to ask, and the form itself.
 */
const REASSURANCE = [
  "Free. There is no version of this you pay for.",
  "Read by a person, not generated by a tool",
  "Yours to keep, whether or not we end up working together",
  // The one line worth saving from LandingProcess, which was cut with it. It
  // was the strongest thing in that section: the reader is not agreeing to
  // anything by sending four fields.
  "Nothing gets built until you have the plan and the cost in front of you",
];



export default function LandingAudit({ variant }: { variant: LpVariant }) {
  return (
    <section
      id={LP_FORM_ANCHOR.replace("#", "")}
      tabIndex={-1}
      className="scroll-mt-20 focus-visible:outline-none bg-[var(--color-surface)] py-24 pb-32 sm:py-28 lg:py-32"
    >
      <div className="cx-main">
        <div className="grid grid-cols-1 gap-12 lg:grid-cols-[1.05fr_0.95fr] lg:gap-16">
          <div>
            <FadeUp>
              <p className="eyebrow mb-5">Free clinic audit</p>
              {/* Was "Find out what is costing your clinic its bookings" — an
                  awkward possessive, and the framing is that the clinic is
                  leaking patients. That is not the argument this site makes: the
                  argument is that the parts are not connected into a system.
                  This states the offer and who keeps the output. */}
              {/* "that is yours either way" read cold has no antecedent — the
                  reader has not been offered a choice at this point in the page,
                  so "either way" points at nothing. This says the same thing
                  plainly, and the reassurance list below no longer repeats it. */}
              {/* Opened on "A free", spending the first slot on an article,
                  and it now sits five sections below LandingAuditPitch's "Free
                  audit:" heading, so leading on "free" twice would be the same
                  word doing the same job twice on one page.
                  
                  "Four questions" is the better opener anyway: it is the actual
                  ask, it is the smallest the ask can be made to sound, and it
                  is the one thing a reader at this depth still wants to know.
                  The sentence below no longer has to introduce it. */}
              <h2 className="text-h2 mb-6 text-[var(--color-ink)]">
                Four questions, and a plan{" "}
                <em className="not-italic text-[var(--color-accent)]">
                  you can use with or without us
                </em>
              </h2>
              <p className="text-body-lg mb-8 max-w-[48ch] text-[var(--color-muted)]">
                That is all we need to start. A written review of your{" "}
                {variant.practiceNoun} comes back to you {LP_TURNAROUND}, with a
                prioritised list of what we would fix first.
              </p>
            </FadeUp>

            

            <FadeUp delay={0.1}>
              <ul
                role="list"
                className="mt-9 flex flex-col gap-2 border-t border-[var(--color-border)] pt-7"
              >
                {REASSURANCE.map((item) => (
                  <li key={item} className="text-body-sm text-[var(--color-muted)]">
                    {item}
                  </li>
                ))}
              </ul>
            </FadeUp>

            <FadeUp delay={0.14}>
              <div className="mt-8 border-t border-[var(--color-border)] pt-7">
                <p className="text-body-sm text-[var(--color-muted)]">
                  Rather write? Email{" "}
                  <a
                    href={`mailto:${siteConfig.email}`}
                    className="font-semibold text-[var(--color-ink)] underline decoration-[var(--color-accent)] decoration-2 underline-offset-4 transition-colors hover:text-[var(--color-accent)]"
                  >
                    {siteConfig.email}
                  </a>
                </p>
              </div>
            </FadeUp>
          </div>

          <FadeUp delay={0.08}>
            {/* The form panel sticks on desktop so it stays reachable while the
                left column is read. */}
            <div className="lg:sticky lg:top-28">
              <div className="card-surface p-6 sm:p-8">
                <p className="text-h4 mb-1.5 text-[var(--color-ink)]">
                  Get your free clinic audit
                </p>
                <p className="text-body-sm mb-6 text-[var(--color-muted)]">
                  No obligation, and nothing to prepare.
                </p>
                <LpAuditForm variant={variant} />
              </div>
            </div>
          </FadeUp>
        </div>
      </div>
    </section>
  );
}
