import LpAuditForm from "@/components/forms/LpAuditForm";
import FadeUp from "@/components/ui/FadeUp";
import { siteConfig } from "@/lib/metadata";
import { LP_FORM_ANCHOR, LP_PHONE, LP_TURNAROUND, type LpVariant } from "@/lib/lp";
import { LpCallButton } from "./LpCtaButton";

/**
 * The conversion section.
 *
 * The left column now says what the audit contains rather than describing it in
 * a paragraph — a visitor who has scrolled this far is deciding whether four
 * questions buys something worth having, and a list answers that faster.
 *
 * Click-to-call sits here too. Someone who reached the bottom of the page and
 * still has not filled in the form may simply prefer to talk.
 */
const AUDIT_CONTENTS = [
  "Where you currently rank for the searches your patients actually type, and who is above you",
  "What your website does with somebody who is ready to book, and how far they get",
  "Whether your Google Business Profile is earning you the map results or sitting idle",
  "What your ad account is paying per enquiry, if you are running one",
  // Deliberately not "and a figure for what it would cost". Listing a price as
  // an audit deliverable obliges every audit response to carry a costed
  // proposal. Cost is answered in the FAQ and in the conversation instead.
  "A prioritised list of what to fix first, in the order we would do it",
];

const REASSURANCE = [
  "Free — there is no version of this you pay for",
  "Read by a person, not generated by a tool",
  "Rolling monthly if you go ahead, no long-term lock-in",
];

export default function LandingAudit({ variant }: { variant: LpVariant }) {
  return (
    <section
      id={LP_FORM_ANCHOR.replace("#", "")}
      tabIndex={-1}
      className="scroll-mt-20 bg-[var(--color-surface)] py-24 pb-32 sm:py-28 lg:py-32"
    >
      <div className="cx-main">
        <div className="grid grid-cols-1 gap-12 lg:grid-cols-[1.05fr_0.95fr] lg:gap-16">
          <div>
            <FadeUp>
              <p className="eyebrow mb-5">Free clinic audit</p>
              {/* Was "Find out what is costing your clinic its bookings" — an
                  awkward possessive, and the framing is that the clinic is
                  leaking patients. That is not the argument this site makes: the
                  argument is that the parts are not connected into a system.
                  This states the offer and who keeps the output. */}
              {/* "that is yours either way" read cold has no antecedent — the
                  reader has not been offered a choice at this point in the page,
                  so "either way" points at nothing. This says the same thing
                  plainly, and the reassurance list below no longer repeats it. */}
              <h2 className="text-h2 mb-6 text-[var(--color-ink)]">
                A free audit of your {variant.practiceNoun}, and a plan{" "}
                <em className="not-italic text-[var(--color-accent)]">
                  you can use with or without us
                </em>
              </h2>
              <p className="text-body-lg mb-8 max-w-[48ch] text-[var(--color-muted)]">
                Four questions is all we need to start. Here is what comes back
                to you {LP_TURNAROUND}.
              </p>
            </FadeUp>

            <FadeUp delay={0.06}>
              <ul role="list" className="flex flex-col gap-3.5">
                {AUDIT_CONTENTS.map((item) => (
                  <li key={item} className="flex items-start gap-3">
                    <svg
                      width="16"
                      height="16"
                      viewBox="0 0 16 16"
                      fill="none"
                      aria-hidden="true"
                      className="mt-1 flex-shrink-0 text-[var(--color-accent)]"
                    >
                      <path
                        d="M3 8l3.5 3.5L13 4"
                        stroke="currentColor"
                        strokeWidth="1.8"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                      />
                    </svg>
                    <span className="text-body text-[var(--color-charcoal)]">
                      {item}
                    </span>
                  </li>
                ))}
              </ul>
            </FadeUp>

            <FadeUp delay={0.1}>
              <ul
                role="list"
                className="mt-9 flex flex-col gap-2 border-t border-[var(--color-border)] pt-7"
              >
                {REASSURANCE.map((item) => (
                  <li key={item} className="text-body-sm text-[var(--color-muted)]">
                    {item}
                  </li>
                ))}
              </ul>
            </FadeUp>

            <FadeUp delay={0.14}>
              <div className="mt-8 flex flex-col gap-3 border-t border-[var(--color-border)] pt-7 sm:flex-row sm:items-center sm:gap-6">
                {LP_PHONE.display ? (
                  <LpCallButton
                    placement="audit-section"
                    size="md"
                    variant="outline"
                  />
                ) : null}
                <p className="text-body-sm text-[var(--color-muted)]">
                  Rather write? Email{" "}
                  <a
                    href={`mailto:${siteConfig.email}`}
                    className="font-semibold text-[var(--color-ink)] underline decoration-[var(--color-accent)] decoration-2 underline-offset-4 transition-colors hover:text-[var(--color-accent)]"
                  >
                    {siteConfig.email}
                  </a>
                </p>
              </div>
            </FadeUp>
          </div>

          <FadeUp delay={0.08}>
            {/* The form panel sticks on desktop so it stays reachable while the
                left column is read. */}
            <div className="lg:sticky lg:top-28">
              <div className="card-surface p-6 sm:p-8">
                <p className="text-h4 mb-1.5 text-[var(--color-ink)]">
                  Book your free audit
                </p>
                <p className="text-body-sm mb-6 text-[var(--color-muted)]">
                  No obligation, and nothing to prepare.
                </p>
                <LpAuditForm variant={variant} />
              </div>
            </div>
          </FadeUp>
        </div>
      </div>
    </section>
  );
}
