import LpAuditForm from "@/components/forms/LpAuditForm";
import FadeUp from "@/components/ui/FadeUp";
import { siteConfig } from "@/lib/metadata";
import { LP_FORM_ANCHOR, LP_TURNAROUND, type LpVariant } from "@/lib/lp";

/**
 * The conversion section.
 *
 * The left column now says what the audit contains rather than describing it in
 * a paragraph — a visitor who has scrolled this far is deciding whether four
 * questions buys something worth having, and a list answers that faster.
 *
 * Email is the only alternative offered. Click-to-call used to sit here for
 * someone who reached the bottom and still had not filled in the form; it was
 * removed with the rest of the phone CTAs — see LP_PHONE.
 */
/*
 * THE FIVE-BULLET LIST THAT WAS HERE IS GONE, cut 9 Sep 2026.
 *
 * LandingAuditPitch, five sections up, already lists seven things the audit
 * looks at. This listed five more about what comes back, so one free offer was
 * explained in fifteen bullets across two sections. That was a third of the
 * reason the page ran to 22 phone screens.
 *
 * What is left below is the part this section owns and the pitch does not: the
 * turnaround, what it costs the reader to ask, and the form itself.
 */
const REASSURANCE = [
  "Free. There is no version of this you pay for.",
  "Read by a person, not generated by a tool",
  "Yours to keep, whether or not we end up working together",
  // The one line worth saving from LandingProcess, which was cut with it. It
  // was the strongest thing in that section: the reader is not agreeing to
  // anything by sending four fields.
  "Nothing gets built until you have the plan and the cost in front of you",
];



export default function LandingAudit({ variant }: { variant: LpVariant }) {
  return (
    <section
      id={LP_FORM_ANCHOR.replace("#", "")}
      tabIndex={-1}
      className="scroll-mt-20 focus-visible:outline-none bg-[var(--color-surface)] py-24 pb-32 sm:py-28 lg:py-32"
    >
      <div className="cx-main">
        <div className="grid grid-cols-1 gap-12 lg:grid-cols-[1.05fr_0.95fr] lg:gap-16">
          <div>
            <FadeUp>
              <p className="eyebrow mb-5">Free clinic audit</p>
              {/* Was "Find out what is costing your clinic its bookings" — an
                  awkward possessive, and the framing is that the clinic is
                  leaking patients. That is not the argument this site makes: the
                  argument is that the parts are not connected into a system.
                  This states the offer and who keeps the output. */}
              {/* "that is yours either way" read cold has no antecedent — the
                  reader has not been offered a choice at this point in the page,
                  so "either way" points at nothing. This says the same thing
                  plainly, and the reassurance list below no longer repeats it. */}
              {/* THIRD VERSION. The first, "A free audit of your clinic, and a
                  plan you can use with or without us", spent its opening slot
                  on an article and led on "free" a second time once
                  LandingAuditPitch took that word.
                  
                  The second, "Four questions, and a plan you can use with or
                  without us", front-loaded the ASK. That is backwards at the
                  point of conversion: a reader who has reached 89% page depth
                  wants the reward, and low friction belongs in the reassurance
                  underneath rather than in the headline. Describing the form's
                  mechanics is the weakest thing this heading can do.
                  
                  This one front-loads the reader's own clinic, which is the
                  most relevant pair of words available anywhere on the page,
                  and puts the value in the accent: prioritisation. Knowing
                  which thing to do first is what a clinic owner with five
                  problems and one budget actually lacks.
                  
                  "Four questions" survives in the sentence below, where it is
                  reassurance about effort rather than a headline. */}
              <h2 className="text-h2 mb-6 text-[var(--color-ink)]">
                Your {variant.practiceNoun},{" "}
                <em className="not-italic text-[var(--color-accent)]">
                  and what we would do first
                </em>
              </h2>
              <p className="text-body-lg mb-8 max-w-[48ch] text-[var(--color-muted)]">
                Four questions is all we need. A written review comes back to
                you {LP_TURNAROUND}.
              </p>
            </FadeUp>

            

            <FadeUp delay={0.1}>
              <ul
                role="list"
                className="mt-9 flex flex-col gap-2 border-t border-[var(--color-border)] pt-7"
              >
                {REASSURANCE.map((item) => (
                  <li key={item} className="text-body-sm text-[var(--color-muted)]">
                    {item}
                  </li>
                ))}
              </ul>
            </FadeUp>

            <FadeUp delay={0.14}>
              <div className="mt-8 border-t border-[var(--color-border)] pt-7">
                <p className="text-body-sm text-[var(--color-muted)]">
                  Rather write? Email{" "}
                  <a
                    href={`mailto:${siteConfig.email}`}
                    className="font-semibold text-[var(--color-ink)] underline decoration-[var(--color-accent)] decoration-2 underline-offset-4 transition-colors hover:text-[var(--color-accent)]"
                  >
                    {siteConfig.email}
                  </a>
                </p>
              </div>
            </FadeUp>
          </div>

          <FadeUp delay={0.08}>
            {/* The form panel sticks on desktop so it stays reachable while the
                left column is read. */}
            <div className="lg:sticky lg:top-28">
              <div className="card-surface p-6 sm:p-8">
                <p className="text-h4 mb-1.5 text-[var(--color-ink)]">
                  Get your free clinic audit
                </p>
                <p className="text-body-sm mb-6 text-[var(--color-muted)]">
                  No obligation, and nothing to prepare.
                </p>
                <LpAuditForm variant={variant} />
              </div>
            </div>
          </FadeUp>
        </div>
      </div>
    </section>
  );
}
